//npc's
{"???", false},{"Treasure Casket", false},{"Achieve Master", false},{"Unity Master", false},{"Novalmauge", false},{"Chumia", false},{"Wooden Door", false},
{"Cell Door", false},{"Couchatorage", false},{"Sewer Lid", false},{"Brugaire", false},{"Jurgenclaus", false},{"Moogle", false},{"Ramblix", false},
{"Goblin Footprint", false},{"GoalPoint", false},{"Grounds Tome", false},{"Geomantic Reservoir", false},{"Survival Guide", false},{"Linkshell Concierge", false},
{"Chat Manual", false},{"Ethereal Junction", false},{"Tatenashi Armor", false},{"Hizamaru Armor", false},{"Ubuginu Armor", false},{"Hachiryu Armor", false},
{"Omodaka Armor", false},{"Bull [Herd1]", false},{"Cow [Herd1]", false},{"Calf [Herd1]", false},{"Bull [Herd2]", false},{"Cow [Herd2]", false},{"Calf [Herd2]", false},
{"Cow [Herd3]", false},{"Calf [Herd3]", false},{"Chigoe", false},{"Pyracmon", false},{"Wraith Bat", false},{"Astral Box", false},{"Slime", false},{"She-Slime", false},
{"Metal Slime", false},{"Hugemaw Harold", false},{"Elated Ovis", false},{"Smiling Ovis", false},{"Estatic Ovis", false},{"Playful Ovis", false},{"Mirthful Cat", false},
{"Andelain", false},{"Croteillard", false},{"Rayochindot", false},{"Cheval River", false},{"Signpost", false},
{"Stone Monument", false},{"Cavernous Maw", false},{"Logging Point", false},{"EFFECTER", false},{"Carbuncle", false},{"Talking Doll", false},{"Field Manual", false},
{"Field Parchment", false},{"Mogball-Local", false},{"Mog-Tablet", false},{"Magivore Ternion", false},{"Stampeding Bison", false},
{"Smile Helper", false},{"Debug", false},{"Slabble", false},{"Planar Rift", false},{"Riftworn Pyxis", false},
//mob's
{"Bloodsucker", true},{"Acid Grease", true},{"Mousse", true},{"Funnel Bats", true},{"Hecatomb Hound", true},{"Werebat", true},{"Haunt", true},{"Garm", true},
{"Dark Aspic", true},{"Sewer Syrup", true},{"Shii", true},{"Drexerion the Condemned", true},{"Phanduron the Condemned", true},{"Blind Bat", true},{"Panna Cotta", true},
{"Nachtmahr", true},{"Dabilla", true},{"Wurdalak", true},{"Arioch", true},{"Gespenst", true},{"Manes", true},{"Bodach", true},{"Garbage Gel", true},{"Pugil", true},
{"Cheval Pugil", true},{"Mud Pugil", true},{"Pug Pugil", true},{"Fighting Pugil", true},{"Wild Rabbit", true},{"Tunnel Worm", true},{"Ding Bats", true},
{"Forest Hare", true},{"Carrion Worm", true},{"Forest Funguar", true},{"Scarab Beetle", true},{"Orcish Fodder", true},{"Mouse Bat", true},{"Orcish Mesmerizer", true},
{"Orcish Grappler", true},{"Goblin Fisher", true},{"Wild Sheep", true},{"Tainted Hound", true},{"Rambukk", true},{"Goblin Thug", true},{"Goblin Weaver", true},
{"Enchanted Bones", true},{"Bomb", true},{"Swamfisk", true},{"Bigmouth Billy", true},{"Goblin Digger", true},{"Pixie", true},{"Gawky Gawain", true},{"Yilbegan", true},
{"Krabkatoa", true},{"Yacumama", true},{"Capricornus", true},{"Quagmire Pugil", true},{"Sunderclaw", true},{"Sarimanok", true},