        private void LoadMA_Click(object sender, EventArgs e)
        {
            if (playerMA.Items.Count > 0)
                playerMA.Items.Clear();

            Dictionary<uint, dynamic> ma = new Dictionary<uint, dynamic>
            {
                #region Magic
                {14, new {text="Poisona",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {15, new {text="Paralyna",job = new Dictionary<int, dynamic> {{3, new {lvl=9}},{20, new {lvl=12}}},}},
                {16, new {text="Blindna",job = new Dictionary<int, dynamic> {{3, new {lvl=14}},{20, new {lvl=17}}},}},
                {17, new {text="Silena",job = new Dictionary<int, dynamic> {{3, new {lvl=19}},{20, new {lvl=22}}},}},
                {18, new {text="Stona",job = new Dictionary<int, dynamic> {{3, new {lvl=39}},{20, new {lvl=50}}},}},
                {19, new {text="Viruna",job = new Dictionary<int, dynamic> {{3, new {lvl=34}},{20, new {lvl=46}}},}},
                {20, new {text="Cursna",job = new Dictionary<int, dynamic> {{3, new {lvl=29}},{20, new {lvl=32}}},}},
                {21, new {text="Holy",job = new Dictionary<int, dynamic> {{3, new {lvl=50}},{7, new {lvl=55}}},}},
                {22, new {text="Holy II",job = new Dictionary<int, dynamic> {{3, new {lvl=95}},{7, new {lvl=99}}},}},
                {23, new {text="Dia",job = new Dictionary<int, dynamic> {{3, new {lvl=3}},{5, new {lvl=1}}},}},
                {24, new {text="Dia II",job = new Dictionary<int, dynamic> {{3, new {lvl=36}},{20, new {lvl=31}}},}},
                {25, new {text="Dia III",job = new Dictionary<int, dynamic> {{20, new {lvl=75}}},}},
                /* {26, new {text="Dia IV",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {27, new {text="Dia V",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {28, new {text="Banish",job = new Dictionary<int, dynamic> {{3, new {lvl=5}},{7, new {lvl=7}}},}},
                {29, new {text="Banish II",job = new Dictionary<int, dynamic> {{3, new {lvl=30}},{7, new {lvl=34}}},}},
                {30, new {text="Banish III",job = new Dictionary<int, dynamic> {{3, new {lvl=65}}},}},
                {33, new {text="Diaga",job = new Dictionary<int, dynamic> {{3, new {lvl=18}},{20, new {lvl=15}}},}},
                /* {34, new {text="Diaga II",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {35, new {text="Diaga III",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {36, new {text="Diaga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {37, new {text="Diaga V",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {38, new {text="Banishga",job = new Dictionary<int, dynamic> {{3, new {lvl=15}}},}},
                {39, new {text="Banishga II",job = new Dictionary<int, dynamic> {{3, new {lvl=40}}},}},
                {43, new {text="Protect",job = new Dictionary<int, dynamic> {{3, new {lvl=7}},{5, new {lvl=7}},{7, new {lvl=10}},{20, new {lvl=10}},{22, new {lvl=20}}},}},
                {44, new {text="Protect II",job = new Dictionary<int, dynamic> {{3, new {lvl=27}},{5, new {lvl=27}},{7, new {lvl=30}},{20, new {lvl=30}},{22, new {lvl=40}}},}},
                {45, new {text="Protect III",job = new Dictionary<int, dynamic> {{3, new {lvl=47}},{5, new {lvl=47}},{7, new {lvl=50}},{20, new {lvl=50}},{22, new {lvl=60}}},}},
                {46, new {text="Protect IV",job = new Dictionary<int, dynamic> {{3, new {lvl=63}},{5, new {lvl=63}},{7, new {lvl=70}},{20, new {lvl=66}},{22, new {lvl=80}}},}},
                {47, new {text="Protect V",job = new Dictionary<int, dynamic> {{3, new {lvl=76}},{5, new {lvl=77}},{7, new {lvl=90}},{20, new {lvl=80}}},}},
                {48, new {text="Shell",job = new Dictionary<int, dynamic> {{3, new {lvl=17}},{5, new {lvl=17}},{7, new {lvl=20}},{20, new {lvl=20}},{22, new {lvl=10}}},}},
                {49, new {text="Shell II",job = new Dictionary<int, dynamic> {{3, new {lvl=37}},{5, new {lvl=37}},{7, new {lvl=40}},{20, new {lvl=40}},{22, new {lvl=30}}},}},
                {50, new {text="Shell III",job = new Dictionary<int, dynamic> {{3, new {lvl=57}},{5, new {lvl=57}},{7, new {lvl=60}},{20, new {lvl=60}},{22, new {lvl=50}}},}},
                {51, new {text="Shell IV",job = new Dictionary<int, dynamic> {{3, new {lvl=68}},{5, new {lvl=68}},{7, new {lvl=80}},{20, new {lvl=71}},{22, new {lvl=70}}},}},
                {52, new {text="Shell V",job = new Dictionary<int, dynamic> {{3, new {lvl=76}},{5, new {lvl=87}},{20, new {lvl=90}},{22, new {lvl=90}}},}},
                {53, new {text="Blink",job = new Dictionary<int, dynamic> {{3, new {lvl=19}},{5, new {lvl=23}},{20, new {lvl=29}},{22, new {lvl=35}}},}},
                {54, new {text="Stoneskin",job = new Dictionary<int, dynamic> {{3, new {lvl=28}},{5, new {lvl=34}},{20, new {lvl=44}},{22, new {lvl=55}}},}},
                {55, new {text="Aquaveil",job = new Dictionary<int, dynamic> {{3, new {lvl=10}},{5, new {lvl=12}},{20, new {lvl=13}},{22, new {lvl=15}}},}},
                {56, new {text="Slow",job = new Dictionary<int, dynamic> {{3, new {lvl=13}},{5, new {lvl=13}}},}},
                {57, new {text="Haste",job = new Dictionary<int, dynamic> {{3, new {lvl=40}},{5, new {lvl=48}}},}},
                {58, new {text="Paralyze",job = new Dictionary<int, dynamic> {{3, new {lvl=4}},{5, new {lvl=6}}},}},
                {59, new {text="Silence",job = new Dictionary<int, dynamic> {{3, new {lvl=15}},{5, new {lvl=18}}},}},
                {60, new {text="Barfire",job = new Dictionary<int, dynamic> {{5, new {lvl=17}}},}},
                {61, new {text="Barblizzard",job = new Dictionary<int, dynamic> {{5, new {lvl=21}}},}},
                {62, new {text="Baraero",job = new Dictionary<int, dynamic> {{5, new {lvl=13}}},}},
                {63, new {text="Barstone",job = new Dictionary<int, dynamic> {{5, new {lvl=5}}},}},
                {64, new {text="Barthunder",job = new Dictionary<int, dynamic> {{5, new {lvl=25}}},}},
                {65, new {text="Barwater",job = new Dictionary<int, dynamic> {{5, new {lvl=9}}},}},
                {66, new {text="Barfira",job = new Dictionary<int, dynamic> {{5, new {lvl=17}}},}},
                {67, new {text="Barblizzara",job = new Dictionary<int, dynamic> {{3, new {lvl=21}}},}},
                {68, new {text="Baraera",job = new Dictionary<int, dynamic> {{3, new {lvl=13}}},}},
                {69, new {text="Barstonra",job = new Dictionary<int, dynamic> {{3, new {lvl=5}}},}},
                {70, new {text="Barthundra",job = new Dictionary<int, dynamic> {{3, new {lvl=25}}},}},
                {71, new {text="Barwatera",job = new Dictionary<int, dynamic> {{3, new {lvl=9}}},}},
                {72, new {text="Barsleep",job = new Dictionary<int, dynamic> {{5, new {lvl=7}}},}},
                {73, new {text="Barpoison",job = new Dictionary<int, dynamic> {{5, new {lvl=10}}},}},
                {74, new {text="Barparalyze",job = new Dictionary<int, dynamic> {{5, new {lvl=12}}},}},
                {75, new {text="Barblind",job = new Dictionary<int, dynamic> {{5, new {lvl=18}}},}},
                {76, new {text="Barsilence",job = new Dictionary<int, dynamic> {{5, new {lvl=23}}},}},
                {77, new {text="Barpetrify",job = new Dictionary<int, dynamic> {{5, new {lvl=43}}},}},
                {78, new {text="Barvirus",job = new Dictionary<int, dynamic> {{5, new {lvl=39}}},}},
                {79, new {text="Slow II",job = new Dictionary<int, dynamic> {{5, new {lvl=75}}},}},
                {80, new {text="Paralyze II",job = new Dictionary<int, dynamic> {{5, new {lvl=75}}},}},
                {84, new {text="Baramnesia",job = new Dictionary<int, dynamic> {{3, new {lvl=78}}},}},
                {85, new {text="Baramnesra",job = new Dictionary<int, dynamic> {{3, new {lvl=78}}},}},
                {86, new {text="Barsleepra",job = new Dictionary<int, dynamic> {{3, new {lvl=7}}},}},
                {87, new {text="Barpoisonra",job = new Dictionary<int, dynamic> {{3, new {lvl=10}}},}},
                {88, new {text="Barparalyzra",job = new Dictionary<int, dynamic> {{3, new {lvl=12}}},}},
                {89, new {text="Barblindra",job = new Dictionary<int, dynamic> {{3, new {lvl=18}}},}},
                {90, new {text="Barsilencera",job = new Dictionary<int, dynamic> {{3, new {lvl=23}}},}},
                {91, new {text="Barpetra",job = new Dictionary<int, dynamic> {{3, new {lvl=43}}},}},
                {92, new {text="Barvira",job = new Dictionary<int, dynamic> {{3, new {lvl=39}}},}},
                {94, new {text="Sacrifice",job = new Dictionary<int, dynamic> {{3, new {lvl=65}}},}},
                {95, new {text="Esuna",job = new Dictionary<int, dynamic> {{3, new {lvl=61}}},}},
                {96, new {text="Auspice",job = new Dictionary<int, dynamic> {{3, new {lvl=55}}},}},
                {97, new {text="Reprisal",job = new Dictionary<int, dynamic> {{7, new {lvl=61}}},}},
                {98, new {text="Repose",job = new Dictionary<int, dynamic> {{3, new {lvl=48}}},}},
                {99, new {text="Sandstorm",job = new Dictionary<int, dynamic> {{20, new {lvl=41}}},}},
                {100, new {text="Enfire",job = new Dictionary<int, dynamic> {{5, new {lvl=24}}},}},
                {101, new {text="Enblizzard",job = new Dictionary<int, dynamic> {{5, new {lvl=22}}},}},
                {102, new {text="Enaero",job = new Dictionary<int, dynamic> {{5, new {lvl=20}}},}},
                {103, new {text="Enstone",job = new Dictionary<int, dynamic> {{5, new {lvl=18}}},}},
                {104, new {text="Enthunder",job = new Dictionary<int, dynamic> {{5, new {lvl=16}}},}},
                {105, new {text="Enwater",job = new Dictionary<int, dynamic> {{5, new {lvl=27}}},}},
                {106, new {text="Phalanx",job = new Dictionary<int, dynamic> {{5, new {lvl=33}},{7, new {lvl=77}},{22, new {lvl=68}}},}},
                {107, new {text="Phalanx II",job = new Dictionary<int, dynamic> {{5, new {lvl=75}}},}},
                {108, new {text="Regen",job = new Dictionary<int, dynamic> {{3, new {lvl=21}},{5, new {lvl=21}},{20, new {lvl=18}},{22, new {lvl=23}}},}},
                {109, new {text="Refresh",job = new Dictionary<int, dynamic> {{5, new {lvl=41}},{22, new {lvl=62}}},}},
                {110, new {text="Regen II",job = new Dictionary<int, dynamic> {{3, new {lvl=44}},{5, new {lvl=76}},{20, new {lvl=37}},{22, new {lvl=48}}},}},
                {111, new {text="Regen III",job = new Dictionary<int, dynamic> {{3, new {lvl=66}},{20, new {lvl=59}},{22, new {lvl=70}}},}},
                {112, new {text="Flash",job = new Dictionary<int, dynamic> {{7, new {lvl=37}},{3, new {lvl=45}},{22, new {lvl=45}}},}},
                {113, new {text="Rainstorm",job = new Dictionary<int, dynamic> {{20, new {lvl=42}}},}},
                {114, new {text="Windstorm",job = new Dictionary<int, dynamic> {{20, new {lvl=43}}},}},
                {115, new {text="Firestorm",job = new Dictionary<int, dynamic> {{20, new {lvl=44}}},}},
                {116, new {text="Hailstorm",job = new Dictionary<int, dynamic> {{20, new {lvl=45}}},}},
                {117, new {text="Thunderstorm",job = new Dictionary<int, dynamic> {{20, new {lvl=46}}},}},
                {118, new {text="Voidstorm",job = new Dictionary<int, dynamic> {{20, new {lvl=47}}},}},
                {119, new {text="Aurorastorm",job = new Dictionary<int, dynamic> {{20, new {lvl=48}}},}},
                {125, new {text="Protectra",job = new Dictionary<int, dynamic> {{3, new {lvl=7}}},}},
                {126, new {text="Protectra II",job = new Dictionary<int, dynamic> {{3, new {lvl=27}}},}},
                {127, new {text="Protectra III",job = new Dictionary<int, dynamic> {{3, new {lvl=47}}},}},
                {128, new {text="Protectra IV",job = new Dictionary<int, dynamic> {{3, new {lvl=63}}},}},
                {129, new {text="Protectra V",job = new Dictionary<int, dynamic> {{3, new {lvl=75}}},}},
                {130, new {text="Shellra",job = new Dictionary<int, dynamic> {{3, new {lvl=17}}},}},
                {131, new {text="Shellra II",job = new Dictionary<int, dynamic> {{3, new {lvl=37}}},}},
                {132, new {text="Shellra III",job = new Dictionary<int, dynamic> {{3, new {lvl=57}}},}},
                {133, new {text="Shellra IV",job = new Dictionary<int, dynamic> {{3, new {lvl=68}}},}},
                {134, new {text="Shellra V",job = new Dictionary<int, dynamic> {{3, new {lvl=75}}},}},
                {135, new {text="Reraise",job = new Dictionary<int, dynamic> {{3, new {lvl=25}},{20, new {lvl=35}}},}},
                {141, new {text="Reraise II",job = new Dictionary<int, dynamic> {{3, new {lvl=56}},{20, new {lvl=70}}},}},
                {142, new {text="Reraise III",job = new Dictionary<int, dynamic> {{3, new {lvl=70}},{20, new {lvl=91}}},}},
                {143, new {text="Erase",job = new Dictionary<int, dynamic> {{3, new {lvl=32}},{5, new {lvl=39}}},}},
                {144, new {text="Fire",job = new Dictionary<int, dynamic> {{4, new {lvl=13}},{5, new {lvl=19}},{8, new {lvl=23}},{20, new {lvl=16}},{21, new {lvl=19}}},}},
                {145, new {text="Fire II",job = new Dictionary<int, dynamic> {{4, new {lvl=38}},{5, new {lvl=50}},{8, new {lvl=60}},{20, new {lvl=42}},{21, new {lvl=46}}},}},
                {146, new {text="Fire III",job = new Dictionary<int, dynamic> {{4, new {lvl=62}},{5, new {lvl=71}},{8, new {lvl=88}},{20, new {lvl=63}},{21, new {lvl=67}}},}},
                {147, new {text="Fire IV",job = new Dictionary<int, dynamic> {{4, new {lvl=73}},{5, new {lvl=86}},{20, new {lvl=73}},{21, new {lvl=85}}},}},
                {148, new {text="Fire V",job = new Dictionary<int, dynamic> {{4, new {lvl=86}},{5, new {lvl=99}},{20, new {lvl=91}},{21, new {lvl=99}}},}},
                {149, new {text="Blizzard",job = new Dictionary<int, dynamic> {{4, new {lvl=17}},{5, new {lvl=24}},{8, new {lvl=29}},{20, new {lvl=20}},{21, new {lvl=24}}},}},
                {150, new {text="Blizzard II",job = new Dictionary<int, dynamic> {{4, new {lvl=42}},{5, new {lvl=55}},{8, new {lvl=66}},{20, new {lvl=46}},{21, new {lvl=50}}},}},
                {151, new {text="Blizzard III",job = new Dictionary<int, dynamic> {{4, new {lvl=64}},{5, new {lvl=73}},{8, new {lvl=92}},{20, new {lvl=66}},{21, new {lvl=70}}},}},
                {152, new {text="Blizzard IV",job = new Dictionary<int, dynamic> {{4, new {lvl=74}},{5, new {lvl=89}},{20, new {lvl=74}},{21, new {lvl=88}}},}},
                {153, new {text="Blizzard V",job = new Dictionary<int, dynamic> {{4, new {lvl=89}},{5, new {lvl=99}},{20, new {lvl=95}},{21, new {lvl=99}}},}},
                /*{154, new {text="Aero",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {155, new {text="Aero II",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {156, new {text="Aero III",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {157, new {text="Aero IV",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {158, new {text="Aero V",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                /*{159, new {text="Stone",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {160, new {text="Stone II",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {161, new {text="Stone III",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {162, new {text="Stone IV",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {163, new {text="Stone V",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                /*{164, new {text="Thunder",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {165, new {text="Thunder II",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {166, new {text="Thunder III",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {167, new {text="Thunder IV",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {168, new {text="Thunder V",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                /*{169, new {text="Water",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {170, new {text="Water II",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {171, new {text="Water III",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {172, new {text="Water IV",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}},
                {173, new {text="Water V",job = new Dictionary<int, dynamic> {{4, new {lvl=90}},{5, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}}, */
                {174, new {text="Firaga",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {175, new {text="Firaga II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {176, new {text="Firaga III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {177, new {text="Firaga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {178, new {text="Firaga V",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {179, new {text="Blizzaga",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {180, new {text="Blizzaga II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {181, new {text="Blizzaga III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {182, new {text="Blizzaga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {183, new {text="Blizzaga V",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {184, new {text="Aeroga",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {185, new {text="Aeroga II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {186, new {text="Aeroga III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {187, new {text="Aeroga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {188, new {text="Aeroga V",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {189, new {text="Stonega",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {190, new {text="Stonega II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {191, new {text="Stonega III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {192, new {text="Stonega IV",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {193, new {text="Stonega V",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {194, new {text="Thundaga",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {195, new {text="Thundaga II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {196, new {text="Thundaga III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {197, new {text="Thundaga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {198, new {text="Thundaga V",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {199, new {text="Waterga",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {200, new {text="Waterga II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {201, new {text="Waterga III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {202, new {text="Waterga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {203, new {text="Waterga V",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {204, new {text="Flare",job = new Dictionary<int, dynamic> {{4, new {lvl=60}}},}},
                {205, new {text="Flare II",job = new Dictionary<int, dynamic> {{4, new {lvl=75}}},}},
                {206, new {text="Freeze",job = new Dictionary<int, dynamic> {{4, new {lvl=50}}},}},
                {207, new {text="Freeze II",job = new Dictionary<int, dynamic> {{4, new {lvl=75}}},}},
                {208, new {text="Tornado",job = new Dictionary<int, dynamic> {{4, new {lvl=52}}},}},
                {209, new {text="Tornado II",job = new Dictionary<int, dynamic> {{4, new {lvl=75}}},}},
                {210, new {text="Quake",job = new Dictionary<int, dynamic> {{4, new {lvl=54}}},}},
                {211, new {text="Quake II",job = new Dictionary<int, dynamic> {{4, new {lvl=75}}},}},
                {212, new {text="Burst",job = new Dictionary<int, dynamic> {{4, new {lvl=56}}},}},
                {213, new {text="Burst II",job = new Dictionary<int, dynamic> {{4, new {lvl=75}}},}},
                {214, new {text="Flood",job = new Dictionary<int, dynamic> {{4, new {lvl=58}}},}},
                {215, new {text="Flood II",job = new Dictionary<int, dynamic> {{4, new {lvl=75}}},}},
                {216, new {text="Gravity",job = new Dictionary<int, dynamic> {{5, new {lvl=21}}},}},
                {217, new {text="Gravity II",job = new Dictionary<int, dynamic> {{5, new {lvl=98}}},}},
                {218, new {text="Meteor",job = new Dictionary<int, dynamic> {{4, new {lvl=99}}},}},
                {219, new {text="Comet",job = new Dictionary<int, dynamic> {{4, new {lvl=94}}},}},
                {220, new {text="Poison",job = new Dictionary<int, dynamic> {{4, new {lvl=3}},{5, new {lvl=5}},{8, new {lvl=6}}},}},
                {221, new {text="Poison II",job = new Dictionary<int, dynamic> {{4, new {lvl=43}},{5, new {lvl=46}},{8, new {lvl=46}}},}},
                /* {222, new {text="Poison III",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {223, new {text="Poison IV",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {224, new {text="Poison V",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {225, new {text="Poisonga",job = new Dictionary<int, dynamic> {{4, new {lvl=24}},{8, new {lvl=26}}},}},
                /* {226, new {text="Poisonga II",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {227, new {text="Poisonga III",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {228, new {text="Poisonga IV",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {229, new {text="Poisonga V",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {230, new {text="Bio",job = new Dictionary<int, dynamic> {{4, new {lvl=10}},{5, new {lvl=10}},{8, new {lvl=15}}},}},
                {231, new {text="Bio II",job = new Dictionary<int, dynamic> {{4, new {lvl=35}},{5, new {lvl=36}},{8, new {lvl=40}}},}},
                {232, new {text="Bio III",job = new Dictionary<int, dynamic> {{5, new {lvl=75}}},}},
                {235, new {text="Burn",job = new Dictionary<int, dynamic> {{4, new {lvl=24}}},}},
                {236, new {text="Frost",job = new Dictionary<int, dynamic> {{4, new {lvl=22}}},}},
                {237, new {text="Choke",job = new Dictionary<int, dynamic> {{4, new {lvl=20}}},}},
                {238, new {text="Rasp",job = new Dictionary<int, dynamic> {{4, new {lvl=18}}},}},
                {239, new {text="Shock",job = new Dictionary<int, dynamic> {{4, new {lvl=16}}},}},
                {240, new {text="Drown",job = new Dictionary<int, dynamic> {{4, new {lvl=27}}},}},
                {242, new {text="Absorb-ACC",job = new Dictionary<int, dynamic> {{8, new {lvl=61}}},}},
                {243, new {text="Absorb-Attri",job = new Dictionary<int, dynamic> {{8, new {lvl=91}}},}},
                {244, new {text="Meteor II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}},{3, new {lvl=6}},{20, new {lvl=10}},{3, new {lvl=6}}},}},
                {245, new {text="Drain",job = new Dictionary<int, dynamic> {{8, new {lvl=10}},{4, new {lvl=12}},{20, new {lvl=21}},{21, new {lvl=15}}},}},
                {246, new {text="Drain II",job = new Dictionary<int, dynamic> {{8, new {lvl=62}}},}},
                {247, new {text="Aspir",job = new Dictionary<int, dynamic> {{8, new {lvl=20}},{4, new {lvl=25}},{20, new {lvl=36}},{21, new {lvl=30}}},}},
                {248, new {text="Aspir II",job = new Dictionary<int, dynamic> {{8, new {lvl=78}},{4, new {lvl=83}},{20, new {lvl=97}},{21, new {lvl=90}}},}},
                {249, new {text="Blaze Spikes",job = new Dictionary<int, dynamic> {{4, new {lvl=10}},{5, new {lvl=20}},{20, new {lvl=30}},{22, new {lvl=45}}},}},
                {250, new {text="Ice Spikes",job = new Dictionary<int, dynamic> {{4, new {lvl=20}},{5, new {lvl=40}},{20, new {lvl=50}},{22, new {lvl=65}}},}},
                {251, new {text="Shock Spikes",job = new Dictionary<int, dynamic> {{4, new {lvl=30}},{5, new {lvl=60}},{20, new {lvl=70}},{22, new {lvl=85}}},}},
                {252, new {text="Stun",job = new Dictionary<int, dynamic> {{4, new {lvl=45}},{8, new {lvl=37}}},}},
                {253, new {text="Sleep",job = new Dictionary<int, dynamic> {{4, new {lvl=20}},{5, new {lvl=25}},{8, new {lvl=30}},{20, new {lvl=30}},{21, new {lvl=35}}},}},
                {254, new {text="Blind",job = new Dictionary<int, dynamic> {{4, new {lvl=4}},{5, new {lvl=8}}},}},
                {255, new {text="Break",job = new Dictionary<int, dynamic> {{4, new {lvl=85}},{5, new {lvl=87}},{8, new {lvl=95}},{20, new {lvl=90}}},}},
                /* {256, new {text="Virus",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {257, new {text="Curse",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {258, new {text="Bind",job = new Dictionary<int, dynamic> {{4, new {lvl=7}},{5, new {lvl=11}},{8, new {lvl=20}}},}},
                {259, new {text="Sleep II",job = new Dictionary<int, dynamic> {{4, new {lvl=41}},{5, new {lvl=46}},{8, new {lvl=56}},{20, new {lvl=65}},{21, new {lvl=70}}},}},
                {260, new {text="Dispel",job = new Dictionary<int, dynamic> {{5, new {lvl=32}},{20, new {lvl=32}}},}},
                {266, new {text="Absorb-STR",job = new Dictionary<int, dynamic> {{8, new {lvl=43}}},}},
                {267, new {text="Absorb-DEX",job = new Dictionary<int, dynamic> {{8, new {lvl=41}}},}},
                {268, new {text="Absorb-VIT",job = new Dictionary<int, dynamic> {{8, new {lvl=35}}},}},
                {269, new {text="Absorb-AGI",job = new Dictionary<int, dynamic> {{8, new {lvl=37}}},}},
                {270, new {text="Absorb-INT",job = new Dictionary<int, dynamic> {{8, new {lvl=39}}},}},
                {271, new {text="Absorb-MND",job = new Dictionary<int, dynamic> {{8, new {lvl=31}}},}},
                {272, new {text="Absorb-CHR",job = new Dictionary<int, dynamic> {{8, new {lvl=33}}},}},
                {273, new {text="Sleepga",job = new Dictionary<int, dynamic> {{4, new {lvl=31}}},}},
                {274, new {text="Sleepga II",job = new Dictionary<int, dynamic> {{4, new {lvl=56}}},}},
                {275, new {text="Absorb-TP",job = new Dictionary<int, dynamic> {{8, new {lvl=45}}},}},
                {276, new {text="Blind II",job = new Dictionary<int, dynamic> {{5, new {lvl=75}}},}},
                {277, new {text="Dread Spikes",job = new Dictionary<int, dynamic> {{8, new {lvl=71}}},}},
                {278, new {text="Geohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=18}}},}},
                {279, new {text="Hydrohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=20}}},}},
                {280, new {text="Anemohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=22}}},}},
                {281, new {text="Pyrohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=24}}},}},
                {282, new {text="Cryohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=26}}},}},
                {283, new {text="Ionohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=28}}},}},
                {284, new {text="Noctohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=30}}},}},
                {285, new {text="Luminohelix",job = new Dictionary<int, dynamic> {{20, new {lvl=32}}},}},
                {286, new {text="Addle",job = new Dictionary<int, dynamic> {{3, new {lvl=93}},{5, new {lvl=83}}},}},
                {287, new {text="Klimaform",job = new Dictionary<int, dynamic> {{20, new {lvl=46}}},}},
                {308, new {text="Animus Augeo",job = new Dictionary<int, dynamic> {{20, new {lvl=85}}},}},
                {309, new {text="Animus Minuo",job = new Dictionary<int, dynamic> {{20, new {lvl=85}}},}},
                {310, new {text="Enlight",job = new Dictionary<int, dynamic> {{7, new {lvl=85}}},}},
                {311, new {text="Endark",job = new Dictionary<int, dynamic> {{8, new {lvl=85}}},}},
                {312, new {text="Enfire II",job = new Dictionary<int, dynamic> {{5, new {lvl=58}}},}},
                {313, new {text="Enblizzard II",job = new Dictionary<int, dynamic> {{5, new {lvl=56}}},}},
                {314, new {text="Enaero II",job = new Dictionary<int, dynamic> {{5, new {lvl=54}}},}},
                {315, new {text="Enstone II",job = new Dictionary<int, dynamic> {{5, new {lvl=52}}},}},
                {316, new {text="Enthunder II",job = new Dictionary<int, dynamic> {{5, new {lvl=50}}},}},
                {317, new {text="Enwater II",job = new Dictionary<int, dynamic> {{5, new {lvl=60}}},}},
                {318, new {text="Monomi: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=25}}},}},
                {319, new {text="Aisha: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=78}}},}},
                {320, new {text="Katon: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=15}}},}},
                {321, new {text="Katon: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=40}}},}},
                {322, new {text="Katon: San",job = new Dictionary<int, dynamic> {{13, new {lvl=75}}},}},
                {323, new {text="Hyoton: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=15}}},}},
                {324, new {text="Hyoton: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=40}}},}},
                {325, new {text="Hyoton: San",job = new Dictionary<int, dynamic> {{13, new {lvl=75}}},}},
                {326, new {text="Huton: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=15}}},}},
                {327, new {text="Huton: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=40}}},}},
                {328, new {text="Huton: San",job = new Dictionary<int, dynamic> {{13, new {lvl=75}}},}},
                {329, new {text="Doton: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=15}}},}},
                {330, new {text="Doton: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=40}}},}},
                {331, new {text="Doton: San",job = new Dictionary<int, dynamic> {{13, new {lvl=75}}},}},
                {332, new {text="Raiton: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=15}}},}},
                {333, new {text="Raiton: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=40}}},}},
                {334, new {text="Raiton: San",job = new Dictionary<int, dynamic> {{13, new {lvl=75}}},}},
                {335, new {text="Suiton: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=15}}},}},
                {336, new {text="Suiton: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=40}}},}},
                {337, new {text="Suiton: San",job = new Dictionary<int, dynamic> {{13, new {lvl=75}}},}},
                {341, new {text="Jubaku: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=30}}},}},
                /* {342, new {text="Jubaku: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}},
                {343, new {text="Jubaku: San",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}}, */
                {344, new {text="Hojo: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=23}}},}},
                {345, new {text="Hojo: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=48}}},}},
                /* {346, new {text="Hojo: San",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}}, */
                {347, new {text="Kurayami: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=19}}},}},
                {348, new {text="Kurayami: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=44}}},}},
                /* {349, new {text="Kurayami: San",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}}, */
                {350, new {text="Dokumori: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=27}}},}},
                /* {351, new {text="Dokumori: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}},
                {352, new {text="Dokumori: San",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}}, */
                {353, new {text="Tonko: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=9}}},}},
                {354, new {text="Tonko: Ni",job = new Dictionary<int, dynamic> {{13, new {lvl=30}}},}},
                /* {355, new {text="Tonko: San",job = new Dictionary<int, dynamic> {{13, new {lvl=0}}},}},
                {356, new {text="Paralyga",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {357, new {text="Slowga",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {358, new {text="Hastega",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {359, new {text="Silencega",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {360, new {text="Dispelga",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {361, new {text="Blindga",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}},
                {362, new {text="Bindga",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {363, new {text="Sleepga",job = new Dictionary<int, dynamic> {{4, new {lvl=31}}},}},
                {364, new {text="Sleepga II",job = new Dictionary<int, dynamic> {{4, new {lvl=56}}},}},
                {365, new {text="Breakga",job = new Dictionary<int, dynamic> {{4, new {lvl=95}}},}},
                /* {366, new {text="Graviga",job = new Dictionary<int, dynamic> {{3, new {lvl=0}},{20, new {lvl=0}}},}}, */
                {367, new {text="Death",job = new Dictionary<int, dynamic> {{4, new {lvl=99}}},}},
                {368, new {text="Foe Requiem",job = new Dictionary<int, dynamic> {{10, new {lvl=7}}},}},
                {369, new {text="Foe Requiem II",job = new Dictionary<int, dynamic> {{10, new {lvl=17}}},}},
                {370, new {text="Foe Requiem III",job = new Dictionary<int, dynamic> {{10, new {lvl=37}}},}},
                {371, new {text="Foe Requiem IV",job = new Dictionary<int, dynamic> {{10, new {lvl=47}}},}},
                {372, new {text="Foe Requiem V",job = new Dictionary<int, dynamic> {{10, new {lvl=57}}},}},
                {373, new {text="Foe Requiem VI",job = new Dictionary<int, dynamic> {{10, new {lvl=67}}},}},
                {374, new {text="Foe Requiem VII",job = new Dictionary<int, dynamic> {{10, new {lvl=76}}},}},
                /* {375, new {text="Foe Requiem VIII",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {376, new {text="Horde Lullaby",job = new Dictionary<int, dynamic> {{10, new {lvl=27}}},}},
                /* {377, new {text="Horde Lullaby II",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {378, new {text="Army's Paeon",job = new Dictionary<int, dynamic> {{10, new {lvl=5}}},}},
                {379, new {text="Army's Paeon II",job = new Dictionary<int, dynamic> {{10, new {lvl=15}}},}},
                {380, new {text="Army's Paeon III",job = new Dictionary<int, dynamic> {{10, new {lvl=35}}},}},
                {381, new {text="Army's Paeon IV",job = new Dictionary<int, dynamic> {{10, new {lvl=45}}},}},
                {382, new {text="Army's Paeon V",job = new Dictionary<int, dynamic> {{10, new {lvl=65}}},}},
                {383, new {text="Army's Paeon VI",job = new Dictionary<int, dynamic> {{10, new {lvl=78}}},}},
                /* {384, new {text="Army's Paeon VII",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}},
                {385, new {text="Army's Paeon VIII",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {386, new {text="Mage's Ballad",job = new Dictionary<int, dynamic> {{10, new {lvl=25}}},}},
                {387, new {text="Mage's Ballad II",job = new Dictionary<int, dynamic> {{10, new {lvl=55}}},}},
                {388, new {text="Mage's Ballad III",job = new Dictionary<int, dynamic> {{10, new {lvl=85}}},}},
                {389, new {text="Knight's Minne",job = new Dictionary<int, dynamic> {{10, new {lvl=1}}},}},
                {390, new {text="Knight's Minne II",job = new Dictionary<int, dynamic> {{10, new {lvl=21}}},}},
                {391, new {text="Knight's Minne III",job = new Dictionary<int, dynamic> {{10, new {lvl=41}}},}},
                {392, new {text="Knight's Minne IV",job = new Dictionary<int, dynamic> {{10, new {lvl=61}}},}},
                {393, new {text="Knight's Minne V",job = new Dictionary<int, dynamic> {{10, new {lvl=80}}},}},
                {394, new {text="Valor Minuet",job = new Dictionary<int, dynamic> {{10, new {lvl=3}}},}},
                {395, new {text="Valor Minuet II",job = new Dictionary<int, dynamic> {{10, new {lvl=23}}},}},
                {396, new {text="Valor Minuet III",job = new Dictionary<int, dynamic> {{10, new {lvl=43}}},}},
                {397, new {text="Valor Minuet IV",job = new Dictionary<int, dynamic> {{10, new {lvl=63}}},}},
                {398, new {text="Valor Minuet V",job = new Dictionary<int, dynamic> {{10, new {lvl=87}}},}},
                {399, new {text="Sword Madrigal",job = new Dictionary<int, dynamic> {{10, new {lvl=11}}},}},
                {400, new {text="Blade Madrigal",job = new Dictionary<int, dynamic> {{10, new {lvl=51}}},}},
                {401, new {text="Hunter's Prelude",job = new Dictionary<int, dynamic> {{10, new {lvl=31}}},}},
                {402, new {text="Archer's Prelude",job = new Dictionary<int, dynamic> {{10, new {lvl=71}}},}},
                {403, new {text="Sheepfoe Mambo",job = new Dictionary<int, dynamic> {{10, new {lvl=13}}},}},
                {404, new {text="Dragonfoe Mambo",job = new Dictionary<int, dynamic> {{10, new {lvl=53}}},}},
                {405, new {text="Fowl Aubade",job = new Dictionary<int, dynamic> {{10, new {lvl=33}}},}},
                {406, new {text="Herb Pastoral",job = new Dictionary<int, dynamic> {{10, new {lvl=9}}},}},
                /* {407, new {text="Chocobo Hum",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {408, new {text="Shining Fantasia",job = new Dictionary<int, dynamic> {{10, new {lvl=56}}},}},
                {409, new {text="Scop's Operetta",job = new Dictionary<int, dynamic> {{10, new {lvl=19}}},}},
                {410, new {text="Puppet's Operetta",job = new Dictionary<int, dynamic> {{10, new {lvl=69}}},}},
                /* {411, new {text="Jester's Operetta",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {412, new {text="Gold Capriccio",job = new Dictionary<int, dynamic> {{10, new {lvl=54}}},}},
                /* {413, new {text="Devotee Serenade",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {414, new {text="Warding Round",job = new Dictionary<int, dynamic> {{10, new {lvl=73}}},}},
                {415, new {text="Goblin Gavotte",job = new Dictionary<int, dynamic> {{10, new {lvl=49}}},}},
                /* {416, new {text="Cactuar Fugue",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}},
                {417, new {text="Moogle Rhapsody",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}},
                {418, new {text="Protected Aria",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {419, new {text="Advancing March",job = new Dictionary<int, dynamic> {{10, new {lvl=29}}},}},
                {420, new {text="Victory March",job = new Dictionary<int, dynamic> {{10, new {lvl=60}}},}},
                {421, new {text="Battlefield Elegy",job = new Dictionary<int, dynamic> {{10, new {lvl=39}}},}},
                {422, new {text="Carnage Elegy",job = new Dictionary<int, dynamic> {{10, new {lvl=59}}},}},
                /* {423, new {text="Massacre Elegy",job = new Dictionary<int, dynamic> {{10, new {lvl=0}}},}}, */
                {424, new {text="Sinewy Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=34}}},}},
                {425, new {text="Dextrous Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=32}}},}},
                {426, new {text="Vivacious Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=30}}},}},
                {427, new {text="Quick Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=28}}},}},
                {428, new {text="Learned Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=26}}},}},
                {429, new {text="Spirited Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=24}}},}},
                {430, new {text="Enchanting Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=22}}},}},
                {431, new {text="Herculean Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=74}}},}},
                {432, new {text="Uncanny Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=72}}},}},
                {433, new {text="Vital Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=70}}},}},
                {434, new {text="Swift Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=68}}},}},
                {435, new {text="Sage Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=66}}},}},
                {436, new {text="Logical Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=64}}},}},
                {437, new {text="Bewitching Etude",job = new Dictionary<int, dynamic> {{10, new {lvl=62}}},}},
                {438, new {text="Fire Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=44}}},}},
                {439, new {text="Ice Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=46}}},}},
                {440, new {text="Wind Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=42}}},}},
                {441, new {text="Earth Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=38}}},}},
                {442, new {text="Lightning Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=48}}},}},
                {443, new {text="Water Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=40}}},}},
                {444, new {text="Light Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=36}}},}},
                {445, new {text="Dark Carol",job = new Dictionary<int, dynamic> {{10, new {lvl=50}}},}},
                {446, new {text="Fire Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=90}}},}},
                {447, new {text="Ice Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=93}}},}},
                {448, new {text="Wind Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=87}}},}},
                {449, new {text="Earth Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=81}}},}},
                {450, new {text="Lightning Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=96}}},}},
                {451, new {text="Water Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=84}}},}},
                {452, new {text="Light Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {453, new {text="Dark Carol II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {454, new {text="Fire Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=20}}},}},
                {455, new {text="Ice Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=22}}},}},
                {456, new {text="Wind Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=18}}},}},
                {457, new {text="Earth Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=14}}},}},
                {458, new {text="Ltng. Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=24}}},}},
                {459, new {text="Water Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=16}}},}},
                {460, new {text="Light Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=10}}},}},
                {461, new {text="Dark Threnody",job = new Dictionary<int, dynamic> {{10, new {lvl=12}}},}},
                {462, new {text="Magic Finale",job = new Dictionary<int, dynamic> {{10, new {lvl=33}}},}},
                {463, new {text="Foe Lullaby",job = new Dictionary<int, dynamic> {{10, new {lvl=16}}},}},
                {464, new {text="Goddess's Hymnus",job = new Dictionary<int, dynamic> {{10, new {lvl=71}}},}},
                {465, new {text="Chocobo Mazurka",job = new Dictionary<int, dynamic> {{10, new {lvl=73}}},}},
                {466, new {text="Maiden's Virelai",job = new Dictionary<int, dynamic> {{10, new {lvl=75}}},}},
                {467, new {text="Raptor Mazurka",job = new Dictionary<int, dynamic> {{10, new {lvl=37}}},}},
                {468, new {text="Foe Sirvente",job = new Dictionary<int, dynamic> {{10, new {lvl=75}}},}},
                {469, new {text="Adventurer's Dirge",job = new Dictionary<int, dynamic> {{10, new {lvl=75}}},}},
                {470, new {text="Sentinel's Scherzo",job = new Dictionary<int, dynamic> {{10, new {lvl=82}}},}},
                {471, new {text="Foe Lullaby II",job = new Dictionary<int, dynamic> {{10, new {lvl=83}}},}},
                {472, new {text="Pining Nocturne",job = new Dictionary<int, dynamic> {{10, new {lvl=95}}},}},
                {473, new {text="Refresh II",job = new Dictionary<int, dynamic> {{5, new {lvl=82}}},}},
                {476, new {text="Crusade",job = new Dictionary<int, dynamic> {{7, new {lvl=88}},{22, new {lvl=88}}},}},
                {477, new {text="Regen IV",job = new Dictionary<int, dynamic> {{3, new {lvl=86}},{20, new {lvl=79}},{22, new {lvl=99}}},}},
                {478, new {text="Embrava",job = new Dictionary<int, dynamic> {{20, new {lvl=5}}},}},
                {479, new {text="Boost-STR",job = new Dictionary<int, dynamic> {{3, new {lvl=93}}},}},
                {480, new {text="Boost-DEX",job = new Dictionary<int, dynamic> {{3, new {lvl=99}}},}},
                {481, new {text="Boost-VIT",job = new Dictionary<int, dynamic> {{3, new {lvl=81}}},}},
                {482, new {text="Boost-AGI",job = new Dictionary<int, dynamic> {{3, new {lvl=90}}},}},
                {483, new {text="Boost-INT",job = new Dictionary<int, dynamic> {{3, new {lvl=96}}},}},
                {484, new {text="Boost-MND",job = new Dictionary<int, dynamic> {{3, new {lvl=84}}},}},
                {485, new {text="Boost-CHR",job = new Dictionary<int, dynamic> {{3, new {lvl=87}}},}},
                {486, new {text="Gain-STR",job = new Dictionary<int, dynamic> {{5, new {lvl=93}}},}},
                {487, new {text="Gain-DEX",job = new Dictionary<int, dynamic> {{5, new {lvl=99}}},}},
                {488, new {text="Gain-VIT",job = new Dictionary<int, dynamic> {{5, new {lvl=81}}},}},
                {489, new {text="Gain-AGI",job = new Dictionary<int, dynamic> {{5, new {lvl=90}}},}},
                {490, new {text="Gain-INT",job = new Dictionary<int, dynamic> {{5, new {lvl=96}}},}},
                {491, new {text="Gain-MND",job = new Dictionary<int, dynamic> {{5, new {lvl=84}}},}},
                {492, new {text="Gain-CHR",job = new Dictionary<int, dynamic> {{5, new {lvl=87}}},}},
                {493, new {text="Temper",job = new Dictionary<int, dynamic> {{5, new {lvl=95}},{22, new {lvl=99}}},}},
                {495, new {text="Adloquium",job = new Dictionary<int, dynamic> {{20, new {lvl=88}}},}},
                {496, new {text="Firaja",job = new Dictionary<int, dynamic> {{4, new {lvl=90}}},}},
                {497, new {text="Blizzaja",job = new Dictionary<int, dynamic> {{4, new {lvl=93}}},}},
                {498, new {text="Aeroja",job = new Dictionary<int, dynamic> {{4, new {lvl=87}}},}},
                {499, new {text="Stoneja",job = new Dictionary<int, dynamic> {{4, new {lvl=81}}},}},
                {500, new {text="Thundaja",job = new Dictionary<int, dynamic> {{4, new {lvl=96}}},}},
                {501, new {text="Waterja",job = new Dictionary<int, dynamic> {{4, new {lvl=84}}},}},
                {502, new {text="Kaustra",job = new Dictionary<int, dynamic> {{20, new {lvl=5}}},}},
                /* {503, new {text="Impact",job = new Dictionary<int, dynamic> {{3, new {lvl=90}},{4, new {lvl=90}},{5, new {lvl=90}},{8, new {lvl=90}},{15, new {lvl=90}},{20, new {lvl=90}},{21, new {lvl=90}}},}}, */
                {504, new {text="Regen V",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {505, new {text="Gekka: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=88}}},}},
                {506, new {text="Yain: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=91}}},}},
                {507, new {text="Myoshu: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=85}}},}},
                {508, new {text="Yurin: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=83}}},}},
                {509, new {text="Kakka: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=93}}},}},
                {510, new {text="Migawari: Ichi",job = new Dictionary<int, dynamic> {{13, new {lvl=88}}},}},
                {511, new {text="Haste II",job = new Dictionary<int, dynamic> {{5, new {lvl=96}}},}},
                {513, new {text="Venom Shell",job = new Dictionary<int, dynamic> {{16, new {lvl=42}}},}},
                {515, new {text="Maelstrom",job = new Dictionary<int, dynamic> {{16, new {lvl=61}}},}},
                {517, new {text="Metallic Body",job = new Dictionary<int, dynamic> {{16, new {lvl=8}}},}},
                {519, new {text="Screwdriver",job = new Dictionary<int, dynamic> {{16, new {lvl=26}}},}},
                {521, new {text="MP Drainkiss",job = new Dictionary<int, dynamic> {{16, new {lvl=42}}},}},
                {522, new {text="Death Ray",job = new Dictionary<int, dynamic> {{16, new {lvl=34}}},}},
                {524, new {text="Sandspin",job = new Dictionary<int, dynamic> {{16, new {lvl=1}}},}},
                {527, new {text="Smite of Rage",job = new Dictionary<int, dynamic> {{16, new {lvl=34}}},}},
                {529, new {text="Bludgeon",job = new Dictionary<int, dynamic> {{16, new {lvl=18}}},}},
                {530, new {text="Refueling",job = new Dictionary<int, dynamic> {{16, new {lvl=48}}},}},
                {531, new {text="Ice Break",job = new Dictionary<int, dynamic> {{16, new {lvl=50}}},}},
                {532, new {text="Blitzstrahl",job = new Dictionary<int, dynamic> {{16, new {lvl=44}}},}},
                {533, new {text="Self-Destruct",job = new Dictionary<int, dynamic> {{16, new {lvl=50}}},}},
                {534, new {text="Mysterious Light",job = new Dictionary<int, dynamic> {{16, new {lvl=40}}},}},
                {535, new {text="Cold Wave",job = new Dictionary<int, dynamic> {{16, new {lvl=52}}},}},
                {536, new {text="Poison Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=22}}},}},
                {537, new {text="Stinking Gas",job = new Dictionary<int, dynamic> {{16, new {lvl=44}}},}},
                {538, new {text="Memento Mori",job = new Dictionary<int, dynamic> {{16, new {lvl=62}}},}},
                {539, new {text="Terror Touch",job = new Dictionary<int, dynamic> {{16, new {lvl=40}}},}},
                {540, new {text="Spinal Cleave",job = new Dictionary<int, dynamic> {{16, new {lvl=63}}},}},
                {541, new {text="Blood Saber",job = new Dictionary<int, dynamic> {{16, new {lvl=48}}},}},
                {542, new {text="Digest",job = new Dictionary<int, dynamic> {{16, new {lvl=36}}},}},
                {543, new {text="Mandibular Bite",job = new Dictionary<int, dynamic> {{16, new {lvl=44}}},}},
                {544, new {text="Cursed Sphere",job = new Dictionary<int, dynamic> {{16, new {lvl=18}}},}},
                {545, new {text="Sickle Slash",job = new Dictionary<int, dynamic> {{16, new {lvl=48}}},}},
                {547, new {text="Cocoon",job = new Dictionary<int, dynamic> {{16, new {lvl=8}}},}},
                {548, new {text="Filamented Hold",job = new Dictionary<int, dynamic> {{16, new {lvl=52}}},}},
                {549, new {text="Pollen",job = new Dictionary<int, dynamic> {{16, new {lvl=1}}},}},
                {551, new {text="Power Attack",job = new Dictionary<int, dynamic> {{16, new {lvl=4}}},}},
                {554, new {text="Death Scissors",job = new Dictionary<int, dynamic> {{16, new {lvl=60}}},}},
                {555, new {text="Magnetite Cloud",job = new Dictionary<int, dynamic> {{16, new {lvl=46}}},}},
                {557, new {text="Eyes On Me",job = new Dictionary<int, dynamic> {{16, new {lvl=61}}},}},
                {560, new {text="Frenetic Rip",job = new Dictionary<int, dynamic> {{16, new {lvl=63}}},}},
                {561, new {text="Frightful Roar",job = new Dictionary<int, dynamic> {{16, new {lvl=50}}},}},
                {563, new {text="Hecatomb Wave",job = new Dictionary<int, dynamic> {{16, new {lvl=54}}},}},
                {564, new {text="Body Slam",job = new Dictionary<int, dynamic> {{16, new {lvl=62}}},}},
                {565, new {text="Radiant Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=54}}},}},
                {567, new {text="Helldive",job = new Dictionary<int, dynamic> {{16, new {lvl=16}}},}},
                {569, new {text="Jet Stream",job = new Dictionary<int, dynamic> {{16, new {lvl=38}}},}},
                {570, new {text="Blood Drain",job = new Dictionary<int, dynamic> {{16, new {lvl=20}}},}},
                {572, new {text="Sound Blast",job = new Dictionary<int, dynamic> {{16, new {lvl=32}}},}},
                {573, new {text="Feather Tickle",job = new Dictionary<int, dynamic> {{16, new {lvl=64}}},}},
                {574, new {text="Feather Barrier",job = new Dictionary<int, dynamic> {{16, new {lvl=56}}},}},
                {575, new {text="Jettatura",job = new Dictionary<int, dynamic> {{16, new {lvl=48}}},}},
                {576, new {text="Yawn",job = new Dictionary<int, dynamic> {{16, new {lvl=64}}},}},
                {577, new {text="Foot Kick",job = new Dictionary<int, dynamic> {{16, new {lvl=1}}},}},
                {578, new {text="Wild Carrot",job = new Dictionary<int, dynamic> {{16, new {lvl=30}}},}},
                {579, new {text="Voracious Trunk",job = new Dictionary<int, dynamic> {{16, new {lvl=64}}},}},
                {581, new {text="Healing Breeze",job = new Dictionary<int, dynamic> {{16, new {lvl=16}}},}},
                {582, new {text="Chaotic Eye",job = new Dictionary<int, dynamic> {{16, new {lvl=32}}},}},
                {584, new {text="Sheep Song",job = new Dictionary<int, dynamic> {{16, new {lvl=16}}},}},
                {585, new {text="Ram Charge",job = new Dictionary<int, dynamic> {{16, new {lvl=73}}},}},
                {587, new {text="Claw Cyclone",job = new Dictionary<int, dynamic> {{16, new {lvl=20}}},}},
                {588, new {text="Lowing",job = new Dictionary<int, dynamic> {{16, new {lvl=71}}},}},
                {589, new {text="Dimensional Death",job = new Dictionary<int, dynamic> {{16, new {lvl=60}}},}},
                {591, new {text="Heat Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=71}}},}},
                {592, new {text="Blank Gaze",job = new Dictionary<int, dynamic> {{16, new {lvl=38}}},}},
                {593, new {text="Magic Fruit",job = new Dictionary<int, dynamic> {{16, new {lvl=58}}},}},
                {594, new {text="Uppercut",job = new Dictionary<int, dynamic> {{16, new {lvl=38}}},}},
                {595, new {text="1000 Needles",job = new Dictionary<int, dynamic> {{16, new {lvl=62}}},}},
                {596, new {text="Pinecone Bomb",job = new Dictionary<int, dynamic> {{16, new {lvl=36}}},}},
                {597, new {text="Sprout Smack",job = new Dictionary<int, dynamic> {{16, new {lvl=4}}},}},
                {598, new {text="Soporific",job = new Dictionary<int, dynamic> {{16, new {lvl=24}}},}},
                {599, new {text="Queasyshroom",job = new Dictionary<int, dynamic> {{16, new {lvl=8}}},}},
                {603, new {text="Wild Oats",job = new Dictionary<int, dynamic> {{16, new {lvl=4}}},}},
                {604, new {text="Bad Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=61}}},}},
                {605, new {text="Geist Wall",job = new Dictionary<int, dynamic> {{16, new {lvl=46}}},}},
                {606, new {text="Awful Eye",job = new Dictionary<int, dynamic> {{16, new {lvl=46}}},}},
                {608, new {text="Frost Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=66}}},}},
                {610, new {text="Infrasonics",job = new Dictionary<int, dynamic> {{16, new {lvl=65}}},}},
                {611, new {text="Disseverment",job = new Dictionary<int, dynamic> {{16, new {lvl=72}}},}},
                {612, new {text="Actinic Burst",job = new Dictionary<int, dynamic> {{16, new {lvl=74}}},}},
                {613, new {text="Reactor Cool",job = new Dictionary<int, dynamic> {{16, new {lvl=74}}},}},
                {614, new {text="Saline Coat",job = new Dictionary<int, dynamic> {{16, new {lvl=72}}},}},
                {615, new {text="Plasma Charge",job = new Dictionary<int, dynamic> {{16, new {lvl=75}}},}},
                {616, new {text="Temporal Shift",job = new Dictionary<int, dynamic> {{16, new {lvl=73}}},}},
                {617, new {text="Vertical Cleave",job = new Dictionary<int, dynamic> {{16, new {lvl=75}}},}},
                {618, new {text="Blastbomb",job = new Dictionary<int, dynamic> {{16, new {lvl=18}}},}},
                {620, new {text="Battle Dance",job = new Dictionary<int, dynamic> {{16, new {lvl=12}}},}},
                {621, new {text="Sandspray",job = new Dictionary<int, dynamic> {{16, new {lvl=61}}},}},
                {622, new {text="Grand Slam",job = new Dictionary<int, dynamic> {{16, new {lvl=30}}},}},
                {623, new {text="Head Butt",job = new Dictionary<int, dynamic> {{16, new {lvl=12}}},}},
                {626, new {text="Bomb Toss",job = new Dictionary<int, dynamic> {{16, new {lvl=28}}},}},
                {628, new {text="Frypan",job = new Dictionary<int, dynamic> {{16, new {lvl=63}}},}},
                {629, new {text="Flying Hip Press",job = new Dictionary<int, dynamic> {{16, new {lvl=58}}},}},
                {631, new {text="Hydro Shot",job = new Dictionary<int, dynamic> {{16, new {lvl=63}}},}},
                {632, new {text="Diamondhide",job = new Dictionary<int, dynamic> {{16, new {lvl=67}}},}},
                {633, new {text="Enervation",job = new Dictionary<int, dynamic> {{16, new {lvl=67}}},}},
                {634, new {text="Light of Penance",job = new Dictionary<int, dynamic> {{16, new {lvl=58}}},}},
                {636, new {text="Warm-Up",job = new Dictionary<int, dynamic> {{16, new {lvl=68}}},}},
                {637, new {text="Firespit",job = new Dictionary<int, dynamic> {{16, new {lvl=68}}},}},
                {638, new {text="Feather Storm",job = new Dictionary<int, dynamic> {{16, new {lvl=12}}},}},
                {640, new {text="Tail Slap",job = new Dictionary<int, dynamic> {{16, new {lvl=69}}},}},
                {641, new {text="Hysteric Barrage",job = new Dictionary<int, dynamic> {{16, new {lvl=69}}},}},
                {642, new {text="Amplification",job = new Dictionary<int, dynamic> {{16, new {lvl=70}}},}},
                {643, new {text="Cannonball",job = new Dictionary<int, dynamic> {{16, new {lvl=70}}},}},
                {644, new {text="Mind Blast",job = new Dictionary<int, dynamic> {{16, new {lvl=73}}},}},
                {645, new {text="Exuviation",job = new Dictionary<int, dynamic> {{16, new {lvl=75}}},}},
                {646, new {text="Magic Hammer",job = new Dictionary<int, dynamic> {{16, new {lvl=74}}},}},
                {647, new {text="Zephyr Mantle",job = new Dictionary<int, dynamic> {{16, new {lvl=65}}},}},
                {648, new {text="Regurgitation",job = new Dictionary<int, dynamic> {{16, new {lvl=69}}},}},
                {650, new {text="Seedspray",job = new Dictionary<int, dynamic> {{16, new {lvl=66}}},}},
                {651, new {text="Corrosive Ooze",job = new Dictionary<int, dynamic> {{16, new {lvl=66}}},}},
                {652, new {text="Spiral Spin",job = new Dictionary<int, dynamic> {{16, new {lvl=60}}},}},
                {653, new {text="Asuran Claws",job = new Dictionary<int, dynamic> {{16, new {lvl=70}}},}},
                {654, new {text="Sub-zero Smash",job = new Dictionary<int, dynamic> {{16, new {lvl=72}}},}},
                {655, new {text="Triumphant Roar",job = new Dictionary<int, dynamic> {{16, new {lvl=71}}},}},
                {656, new {text="Acrid Stream",job = new Dictionary<int, dynamic> {{16, new {lvl=77}}},}},
                {657, new {text="Blazing Bound",job = new Dictionary<int, dynamic> {{16, new {lvl=80}}},}},
                {658, new {text="Plenilune Embrace",job = new Dictionary<int, dynamic> {{16, new {lvl=76}}},}},
                {659, new {text="Demoralizing Roar",job = new Dictionary<int, dynamic> {{16, new {lvl=80}}},}},
                {660, new {text="Cimicine Discharge",job = new Dictionary<int, dynamic> {{16, new {lvl=78}}},}},
                {661, new {text="Animating Wail",job = new Dictionary<int, dynamic> {{16, new {lvl=79}}},}},
                {662, new {text="Battery Charge",job = new Dictionary<int, dynamic> {{16, new {lvl=79}}},}},
                {663, new {text="Leafstorm",job = new Dictionary<int, dynamic> {{16, new {lvl=77}}},}},
                {664, new {text="Regeneration",job = new Dictionary<int, dynamic> {{16, new {lvl=78}}},}},
                {665, new {text="Final Sting",job = new Dictionary<int, dynamic> {{16, new {lvl=81}}},}},
                {666, new {text="Goblin Rush",job = new Dictionary<int, dynamic> {{16, new {lvl=81}}},}},
                {667, new {text="Vanity Dive",job = new Dictionary<int, dynamic> {{16, new {lvl=82}}},}},
                {668, new {text="Magic Barrier",job = new Dictionary<int, dynamic> {{16, new {lvl=82}}},}},
                {669, new {text="Whirl of Rage",job = new Dictionary<int, dynamic> {{16, new {lvl=83}}},}},
                {670, new {text="Benthic Typhoon",job = new Dictionary<int, dynamic> {{16, new {lvl=83}}},}},
                {671, new {text="Auroral Drape",job = new Dictionary<int, dynamic> {{16, new {lvl=84}}},}},
                {672, new {text="Osmosis",job = new Dictionary<int, dynamic> {{16, new {lvl=84}}},}},
                {673, new {text="Quad. Continuum",job = new Dictionary<int, dynamic> {{16, new {lvl=85}}},}},
                {674, new {text="Fantod",job = new Dictionary<int, dynamic> {{16, new {lvl=85}}},}},
                {675, new {text="Thermal Pulse",job = new Dictionary<int, dynamic> {{16, new {lvl=86}}},}},
                {677, new {text="Empty Thrash",job = new Dictionary<int, dynamic> {{16, new {lvl=87}}},}},
                {678, new {text="Dream Flower",job = new Dictionary<int, dynamic> {{16, new {lvl=87}}},}},
                {679, new {text="Occultation",job = new Dictionary<int, dynamic> {{16, new {lvl=88}}},}},
                {680, new {text="Charged Whisker",job = new Dictionary<int, dynamic> {{16, new {lvl=88}}},}},
                {681, new {text="Winds of Promy.",job = new Dictionary<int, dynamic> {{16, new {lvl=89}}},}},
                {682, new {text="Delta Thrust",job = new Dictionary<int, dynamic> {{16, new {lvl=89}}},}},
                {683, new {text="Evryone. Grudge",job = new Dictionary<int, dynamic> {{16, new {lvl=90}}},}},
                {684, new {text="Reaving Wind",job = new Dictionary<int, dynamic> {{16, new {lvl=90}}},}},
                {685, new {text="Barrier Tusk",job = new Dictionary<int, dynamic> {{16, new {lvl=91}}},}},
                {686, new {text="Mortal Ray",job = new Dictionary<int, dynamic> {{16, new {lvl=91}}},}},
                {687, new {text="Water Bomb",job = new Dictionary<int, dynamic> {{16, new {lvl=92}}},}},
                {688, new {text="Heavy Strike",job = new Dictionary<int, dynamic> {{16, new {lvl=92}}},}},
                {689, new {text="Dark Orb",job = new Dictionary<int, dynamic> {{16, new {lvl=93}}},}},
                {690, new {text="White Wind",job = new Dictionary<int, dynamic> {{16, new {lvl=94}}},}},
                {692, new {text="Sudden Lunge",job = new Dictionary<int, dynamic> {{16, new {lvl=95}}},}},
                {693, new {text="Quadrastrike",job = new Dictionary<int, dynamic> {{16, new {lvl=96}}},}},
                {694, new {text="Vapor Spray",job = new Dictionary<int, dynamic> {{16, new {lvl=96}}},}},
                {695, new {text="Thunder Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=97}}},}},
                {696, new {text="O. Counterstance",job = new Dictionary<int, dynamic> {{16, new {lvl=98}}},}},
                {697, new {text="Amorphic Spikes",job = new Dictionary<int, dynamic> {{16, new {lvl=98}}},}},
                {698, new {text="Wind Breath",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {699, new {text="Barbed Crescent",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {700, new {text="Nat. Meditation",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {701, new {text="Tem. Upheaval",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {702, new {text="Rending Deluge",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {703, new {text="Embalming Earth",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {704, new {text="Paralyzing Triad",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {705, new {text="Foul Waters",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {706, new {text="Glutinous Dart",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {707, new {text="Retinal Glare",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {708, new {text="Subduction",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {709, new {text="Thrashing Assault",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {710, new {text="Erratic Flutter",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {711, new {text="Restoral",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {712, new {text="Rail Cannon",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {713, new {text="Diffusion Ray",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {714, new {text="Sinker Drill",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {715, new {text="Molting Plumage",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {716, new {text="Nectarous Deluge",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {717, new {text="Sweeping Gouge",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {718, new {text="Atra. Libations",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {719, new {text="Searing Tempest",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {720, new {text="Spectral Floe",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {721, new {text="Anvil Lightning",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {722, new {text="Entomb",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {723, new {text="Saurian Slide",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {724, new {text="Palling Salvo",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {725, new {text="Blinding Fulgor",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {726, new {text="Scouring Spate",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {727, new {text="Silent Storm",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {728, new {text="Tenebral Crush",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {736, new {text="Thunderbolt",job = new Dictionary<int, dynamic> {{16, new {lvl=95}}},}},
                {737, new {text="Harden Shell",job = new Dictionary<int, dynamic> {{16, new {lvl=95}}},}},
                {738, new {text="Absolute Terror",job = new Dictionary<int, dynamic> {{16, new {lvl=96}}},}},
                {739, new {text="Gates of Hades",job = new Dictionary<int, dynamic> {{16, new {lvl=97}}},}},
                {740, new {text="Tourbillion",job = new Dictionary<int, dynamic> {{16, new {lvl=97}}},}},
                {741, new {text="Pyric Bulwark",job = new Dictionary<int, dynamic> {{16, new {lvl=98}}},}},
                {742, new {text="Bilgestorm",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {743, new {text="Bloodrake",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {744, new {text="Droning Whirlwind",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {745, new {text="Carcharian Verve",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {746, new {text="Blistering Roar",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {747, new {text="Uproot",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {748, new {text="Crashing Thunder",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {749, new {text="Polar Roar",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {750, new {text="Mighty Guard",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {751, new {text="Cruel Joke",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {752, new {text="Cesspool",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                {753, new {text="Tearing Gust",job = new Dictionary<int, dynamic> {{16, new {lvl=99}}},}},
                /* {768, new {text="Indi-Regen",job = new Dictionary<int, dynamic> {{21, new {lvl=15}}},}},
                {769, new {text="Indi-Poison",job = new Dictionary<int, dynamic> {{21, new {lvl=1}}},}},
                {770, new {text="Indi-Refresh",job = new Dictionary<int, dynamic> {{21, new {lvl=30}}},}},
                {771, new {text="Indi-Haste",job = new Dictionary<int, dynamic> {{21, new {lvl=93}}},}},
                {772, new {text="Indi-STR",job = new Dictionary<int, dynamic> {{21, new {lvl=48}}},}},
                {773, new {text="Indi-DEX",job = new Dictionary<int, dynamic> {{21, new {lvl=45}}},}},
                {774, new {text="Indi-VIT",job = new Dictionary<int, dynamic> {{21, new {lvl=42}}},}},
                {775, new {text="Indi-AGI",job = new Dictionary<int, dynamic> {{21, new {lvl=39}}},}},
                {776, new {text="Indi-INT",job = new Dictionary<int, dynamic> {{21, new {lvl=36}}},}},
                {777, new {text="Indi-MND",job = new Dictionary<int, dynamic> {{21, new {lvl=33}}},}},
                {778, new {text="Indi-CHR",job = new Dictionary<int, dynamic> {{21, new {lvl=30}}},}},
                {779, new {text="Indi-Fury",job = new Dictionary<int, dynamic> {{21, new {lvl=34}}},}},
                {780, new {text="Indi-Barrier",job = new Dictionary<int, dynamic> {{21, new {lvl=28}}},}},
                {781, new {text="Indi-Acumen",job = new Dictionary<int, dynamic> {{21, new {lvl=46}}},}},
                {782, new {text="Indi-Fend",job = new Dictionary<int, dynamic> {{21, new {lvl=40}}},}},
                {783, new {text="Indi-Precision",job = new Dictionary<int, dynamic> {{21, new {lvl=10}}},}},
                {784, new {text="Indi-Voidance",job = new Dictionary<int, dynamic> {{21, new {lvl=4}}},}},
                {785, new {text="Indi-Focus",job = new Dictionary<int, dynamic> {{21, new {lvl=22}}},}},
                {786, new {text="Indi-Attunement",job = new Dictionary<int, dynamic> {{21, new {lvl=16}}},}},
                {787, new {text="Indi-Wilt",job = new Dictionary<int, dynamic> {{21, new {lvl=82}}},}},
                {788, new {text="Indi-Frailty",job = new Dictionary<int, dynamic> {{21, new {lvl=76}}},}},
                {789, new {text="Indi-Fade",job = new Dictionary<int, dynamic> {{21, new {lvl=94}}},}},
                {790, new {text="Indi-Malaise",job = new Dictionary<int, dynamic> {{21, new {lvl=88}}},}},
                {791, new {text="Indi-Slip",job = new Dictionary<int, dynamic> {{21, new {lvl=58}}},}},
                {792, new {text="Indi-Torpor",job = new Dictionary<int, dynamic> {{21, new {lvl=52}}},}},
                {793, new {text="Indi-Vex",job = new Dictionary<int, dynamic> {{21, new {lvl=70}}},}},
                {794, new {text="Indi-Languor",job = new Dictionary<int, dynamic> {{21, new {lvl=64}}},}},
                {795, new {text="Indi-Slow",job = new Dictionary<int, dynamic> {{21, new {lvl=48}}},}},
                {796, new {text="Indi-Paralysis",job = new Dictionary<int, dynamic> {{21, new {lvl=68}}},}},
                {797, new {text="Indi-Gravity",job = new Dictionary<int, dynamic> {{21, new {lvl=88}}},}},
                {798, new {text="Geo-Regen",job = new Dictionary<int, dynamic> {{21, new {lvl=19}}},}},
                {799, new {text="Geo-Poison",job = new Dictionary<int, dynamic> {{21, new {lvl=5}}},}},
                {800, new {text="Geo-Refresh",job = new Dictionary<int, dynamic> {{21, new {lvl=34}}},}},
                {801, new {text="Geo-Haste",job = new Dictionary<int, dynamic> {{21, new {lvl=97}}},}},
                {802, new {text="Geo-STR",job = new Dictionary<int, dynamic> {{21, new {lvl=52}}},}},
                {803, new {text="Geo-DEX",job = new Dictionary<int, dynamic> {{21, new {lvl=49}}},}},
                {804, new {text="Geo-VIT",job = new Dictionary<int, dynamic> {{21, new {lvl=46}}},}},
                {805, new {text="Geo-AGI",job = new Dictionary<int, dynamic> {{21, new {lvl=43}}},}},
                {806, new {text="Geo-INT",job = new Dictionary<int, dynamic> {{21, new {lvl=40}}},}},
                {807, new {text="Geo-MND",job = new Dictionary<int, dynamic> {{21, new {lvl=37}}},}},
                {808, new {text="Geo-CHR",job = new Dictionary<int, dynamic> {{21, new {lvl=34}}},}},
                {809, new {text="Geo-Fury",job = new Dictionary<int, dynamic> {{21, new {lvl=38}}},}},
                {810, new {text="Geo-Barrier",job = new Dictionary<int, dynamic> {{21, new {lvl=32}}},}},
                {811, new {text="Geo-Acumen",job = new Dictionary<int, dynamic> {{21, new {lvl=50}}},}},
                {812, new {text="Geo-Fend",job = new Dictionary<int, dynamic> {{21, new {lvl=44}}},}},
                {813, new {text="Geo-Precision",job = new Dictionary<int, dynamic> {{21, new {lvl=14}}},}},
                {814, new {text="Geo-Voidance",job = new Dictionary<int, dynamic> {{21, new {lvl=8}}},}},
                {815, new {text="Geo-Focus",job = new Dictionary<int, dynamic> {{21, new {lvl=26}}},}},
                {816, new {text="Geo-Attunement",job = new Dictionary<int, dynamic> {{21, new {lvl=20}}},}},
                {817, new {text="Geo-Wilt",job = new Dictionary<int, dynamic> {{21, new {lvl=86}}},}},
                {818, new {text="Geo-Frailty",job = new Dictionary<int, dynamic> {{21, new {lvl=80}}},}},
                {819, new {text="Geo-Fade",job = new Dictionary<int, dynamic> {{21, new {lvl=98}}},}},
                {820, new {text="Geo-Malaise",job = new Dictionary<int, dynamic> {{21, new {lvl=92}}},}},
                {821, new {text="Geo-Slip",job = new Dictionary<int, dynamic> {{21, new {lvl=62}}},}},
                {822, new {text="Geo-Torpor",job = new Dictionary<int, dynamic> {{21, new {lvl=56}}},}},
                {823, new {text="Geo-Vex",job = new Dictionary<int, dynamic> {{21, new {lvl=74}}},}},
                {824, new {text="Geo-Languor",job = new Dictionary<int, dynamic> {{21, new {lvl=68}}},}},
                {825, new {text="Geo-Slow",job = new Dictionary<int, dynamic> {{21, new {lvl=52}}},}},
                {826, new {text="Geo-Paralysis",job = new Dictionary<int, dynamic> {{21, new {lvl=72}}},}},
                {827, new {text="Geo-Gravity",job = new Dictionary<int, dynamic> {{21, new {lvl=92}}},}}, */
                {828, new {text="Fira",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {829, new {text="Fira II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {830, new {text="Blizzara",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {831, new {text="Blizzara II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {832, new {text="Aerora",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {833, new {text="Aerora II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {834, new {text="Stonera",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {835, new {text="Stonera II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {836, new {text="Thundara",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {837, new {text="Thundara II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {838, new {text="Watera",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {839, new {text="Watera II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {840, new {text="Foil",job = new Dictionary<int, dynamic> {{22, new {lvl=58}}},}},
                {841, new {text="Distract",job = new Dictionary<int, dynamic> {{5, new {lvl=35}}},}},
                {842, new {text="Distract II",job = new Dictionary<int, dynamic> {{5, new {lvl=85}}},}},
                {843, new {text="Frazzle",job = new Dictionary<int, dynamic> {{5, new {lvl=42}}},}},
                {844, new {text="Frazzle II",job = new Dictionary<int, dynamic> {{5, new {lvl=92}}},}},
                {845, new {text="Flurry",job = new Dictionary<int, dynamic> {{5, new {lvl=48}}},}},
                {846, new {text="Flurry II",job = new Dictionary<int, dynamic> {{5, new {lvl=96}}},}},
                {848, new {text="Reraise IV",job = new Dictionary<int, dynamic> {{3, new {lvl=99}}},}},
                {849, new {text="Fire VI",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {850, new {text="Blizzard VI",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {851, new {text="Aero VI",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {852, new {text="Stone VI",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {853, new {text="Thunder VI",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {854, new {text="Water VI",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {855, new {text="Enlight II",job = new Dictionary<int, dynamic> {{7, new {lvl=99}}},}},
                {856, new {text="Endark II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {857, new {text="Sandstorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {858, new {text="Rainstorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {859, new {text="Windstorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {860, new {text="Firestorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {861, new {text="Hailstorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {862, new {text="Thunderstorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {863, new {text="Voidstorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {864, new {text="Aurorastorm II",job = new Dictionary<int, dynamic> {{20, new {lvl=99}}},}},
                {865, new {text="Fira III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {866, new {text="Blizzara III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {867, new {text="Aerora III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {868, new {text="Stonera III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {869, new {text="Thundara III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {870, new {text="Watera III",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {871, new {text="Fire Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {872, new {text="Ice Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {873, new {text="Wind Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {874, new {text="Earth Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {875, new {text="Ltng. Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {876, new {text="Water Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {877, new {text="Light Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {878, new {text="Dark Threnody II",job = new Dictionary<int, dynamic> {{10, new {lvl=99}}},}},
                {879, new {text="Inundation",job = new Dictionary<int, dynamic> {{5, new {lvl=64}}},}},
                {880, new {text="Drain III",job = new Dictionary<int, dynamic> {{8, new {lvl=99}}},}},
                {881, new {text="Aspir III",job = new Dictionary<int, dynamic> {{4, new {lvl=99}},{21, new {lvl=99}}},}},
                {882, new {text="Distract III",job = new Dictionary<int, dynamic> {{5, new {lvl=99}}},}},
                {883, new {text="Frazzle III",job = new Dictionary<int, dynamic> {{5, new {lvl=99}}},}},
                {884, new {text="Addle II",job = new Dictionary<int, dynamic> {{5, new {lvl=99}}},}},
                {885, new {text="Geohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {886, new {text="Hydrohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {887, new {text="Anemohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {888, new {text="Pyrohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {889, new {text="Cryohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {890, new {text="Ionohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {891, new {text="Noctohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {892, new {text="Luminohelix II",job = new Dictionary<int, dynamic> {{3, new {lvl=6}},{20, new {lvl=10}}},}},
                {894, new {text="Refresh III",job = new Dictionary<int, dynamic> {{5, new {lvl=99}}},}},
                {895, new {text="Temper II",job = new Dictionary<int, dynamic> {{5, new {lvl=99}}},}},
                
                #endregion
            };
            
            #region load MJ (main job)

            foreach( KeyValuePair<uint, dynamic> kvp in ma)
                {
                    if (PlayerInfo.HasSpell(kvp.Key) && kvp.Value.job.ContainsKey(PlayerInfo.MainJob) &&
                        kvp.Value.job[PlayerInfo.MainJob].lvl <= PlayerInfo.MainJobLevel &&
                        !playerMA.Items.Contains(kvp.Value.text))
                    {
                        playerMA.Items.AddRange(new object[]
                        {
                            kvp.Value.text,
                        });
                    
                    }
                }
            
            #endregion
            #region load SJ (sub job)
            
            foreach( KeyValuePair<uint, dynamic> kvp in ma)
                {
                    if (PlayerInfo.HasSpell(kvp.Key) && kvp.Value.job.ContainsKey(PlayerInfo.SubJob) &&
                        kvp.Value.job[PlayerInfo.SubJob].lvl <= PlayerInfo.SubJobLevel &&
                        !playerMA.Items.Contains(kvp.Value.text))
                    {
                        playerMA.Items.AddRange(new object[]
                        {
                            kvp.Value.text,
                        });
                    
                    }
                }
            #endregion
        }

        private void ClearMA_Click(object sender, EventArgs e)
        {
            playerMA.Items.Clear();
        }